package com.algaworks.comercial.model;

// Generated 23/03/2016 10:12:00 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Aquisicao generated by hbm2java
 */
@Entity
@Table(name = "aquisicao", catalog = "semana")
public class Aquisicao implements java.io.Serializable {

	private Long id;
	private Maquina maquina;
	private Date dataInicial;
	private int quantidade;
	private float valor;

	public Aquisicao() {
	}

	public Aquisicao(int quantidade, float valor) {
		this.quantidade = quantidade;
		this.valor = valor;
	}

	public Aquisicao(Maquina maquina, Date dataInicial, int quantidade,
			float valor) {
		this.maquina = maquina;
		this.dataInicial = dataInicial;
		this.quantidade = quantidade;
		this.valor = valor;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "maquina_id")
	public Maquina getMaquina() {
		return this.maquina;
	}

	public void setMaquina(Maquina maquina) {
		this.maquina = maquina;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dataInicial", length = 10)
	public Date getDataInicial() {
		return this.dataInicial;
	}

	public void setDataInicial(Date dataInicial) {
		this.dataInicial = dataInicial;
	}

	@Column(name = "quantidade", nullable = false)
	public int getQuantidade() {
		return this.quantidade;
	}

	public void setQuantidade(int quantidade) {
		this.quantidade = quantidade;
	}

	@Column(name = "valor", nullable = false, precision = 12, scale = 0)
	public float getValor() {
		return this.valor;
	}

	public void setValor(float valor) {
		this.valor = valor;
	}

}
