package com.algaworks.comercial.model;

// Generated 23/03/2016 10:12:00 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ConsumoProducao generated by hbm2java
 */
@Entity
@Table(name = "consumo_producao", catalog = "semana")
public class ConsumoProducao implements java.io.Serializable {

	private Long id;
	private String descricao;
	private double valor;
	private Set<Producao> producaos = new HashSet<Producao>(0);

	public ConsumoProducao() {
	}

	public ConsumoProducao(double valor) {
		this.valor = valor;
	}

	public ConsumoProducao(String descricao, double valor,
			Set<Producao> producaos) {
		this.descricao = descricao;
		this.valor = valor;
		this.producaos = producaos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "descricao")
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "valor", nullable = false, precision = 22, scale = 0)
	public double getValor() {
		return this.valor;
	}

	public void setValor(double valor) {
		this.valor = valor;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "consumoProducao")
	public Set<Producao> getProducaos() {
		return this.producaos;
	}

	public void setProducaos(Set<Producao> producaos) {
		this.producaos = producaos;
	}

}
