package com.algaworks.comercial.model;

// Generated 23/03/2016 10:12:00 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estado generated by hbm2java
 */
@Entity
@Table(name = "estado", catalog = "semana")
@NamedQueries({
	@NamedQuery(name="Estado.findSigla", query="select d from Estado d where d.uf = :uf")
})
public class Estado implements java.io.Serializable {

	private String uf;
	private String descricao;
	private String status;
	private Set<Municipio> municipios = new HashSet<Municipio>(0);
	public static final String FIND_UF= "Estado.findSigla";

	public Estado() {
	}

	public Estado(String uf) {
		this.uf = uf;
	}

	public Estado(String uf, String descricao, String status,
			Set<Municipio> municipios) {
		this.uf = uf;
		this.descricao = descricao;
		this.status = status;
		this.municipios = municipios;
	}

	@Id
	@Column(name = "uf", unique = true, nullable = false)
	public String getUf() {
		return this.uf;
	}

	public void setUf(String uf) {
		this.uf = uf;
	}

	@Column(name = "descricao")
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "status")
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estado")
	public Set<Municipio> getMunicipios() {
		return this.municipios;
	}

	public void setMunicipios(Set<Municipio> municipios) {
		this.municipios = municipios;
	}

}
