package com.algaworks.comercial.model;

// Generated 23/03/2016 10:12:00 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EstoqueMPrimaId generated by hbm2java
 */
@Embeddable
public class EstoqueMPrimaId implements java.io.Serializable {

	private long MPrimaId;
	private long estoqueId;

	public EstoqueMPrimaId() {
	}

	public EstoqueMPrimaId(long MPrimaId, long estoqueId) {
		this.MPrimaId = MPrimaId;
		this.estoqueId = estoqueId;
	}

	@Column(name = "m_prima_id", nullable = false)
	public long getMPrimaId() {
		return this.MPrimaId;
	}

	public void setMPrimaId(long MPrimaId) {
		this.MPrimaId = MPrimaId;
	}

	@Column(name = "estoque_id", nullable = false)
	public long getEstoqueId() {
		return this.estoqueId;
	}

	public void setEstoqueId(long estoqueId) {
		this.estoqueId = estoqueId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EstoqueMPrimaId))
			return false;
		EstoqueMPrimaId castOther = (EstoqueMPrimaId) other;

		return (this.getMPrimaId() == castOther.getMPrimaId())
				&& (this.getEstoqueId() == castOther.getEstoqueId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getMPrimaId();
		result = 37 * result + (int) this.getEstoqueId();
		return result;
	}

}
