package com.algaworks.comercial.model;

// Generated 23/03/2016 10:12:00 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EstoqueProdutoId generated by hbm2java
 */
@Embeddable
public class EstoqueProdutoId implements java.io.Serializable {

	private long produtoId;
	private long estoqueId;

	public EstoqueProdutoId() {
	}

	public EstoqueProdutoId(long produtoId, long estoqueId) {
		this.produtoId = produtoId;
		this.estoqueId = estoqueId;
	}

	@Column(name = "produto_id", nullable = false)
	public long getProdutoId() {
		return this.produtoId;
	}

	public void setProdutoId(long produtoId) {
		this.produtoId = produtoId;
	}

	@Column(name = "estoque_id", nullable = false)
	public long getEstoqueId() {
		return this.estoqueId;
	}

	public void setEstoqueId(long estoqueId) {
		this.estoqueId = estoqueId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EstoqueProdutoId))
			return false;
		EstoqueProdutoId castOther = (EstoqueProdutoId) other;

		return (this.getProdutoId() == castOther.getProdutoId())
				&& (this.getEstoqueId() == castOther.getEstoqueId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getProdutoId();
		result = 37 * result + (int) this.getEstoqueId();
		return result;
	}

}
