package com.algaworks.comercial.model;

// Generated 23/03/2016 10:12:00 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EstoqueMPrima generated by hbm2java
 */
@Entity
@Table(name = "estoque_m_prima", catalog = "semana")
public class EstoqueMPrima implements java.io.Serializable {

	private EstoqueMPrimaId id;
	private Estoque estoque;
	private MPrima MPrima;
	private String notaFiscal;
	private int numSerie;
	private String tipoMovimento;
	private Date dataMovimento;

	public EstoqueMPrima() {
	}

	public EstoqueMPrima(EstoqueMPrimaId id, Estoque estoque, MPrima MPrima,
			int numSerie) {
		this.id = id;
		this.estoque = estoque;
		this.MPrima = MPrima;
		this.numSerie = numSerie;
	}

	public EstoqueMPrima(EstoqueMPrimaId id, Estoque estoque, MPrima MPrima,
			String notaFiscal, int numSerie, String tipoMovimento,
			Date dataMovimento) {
		this.id = id;
		this.estoque = estoque;
		this.MPrima = MPrima;
		this.notaFiscal = notaFiscal;
		this.numSerie = numSerie;
		this.tipoMovimento = tipoMovimento;
		this.dataMovimento = dataMovimento;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "MPrimaId", column = @Column(name = "m_prima_id", nullable = false)),
			@AttributeOverride(name = "estoqueId", column = @Column(name = "estoque_id", nullable = false)) })
	public EstoqueMPrimaId getId() {
		return this.id;
	}

	public void setId(EstoqueMPrimaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "estoque_id", nullable = false, insertable = false, updatable = false)
	public Estoque getEstoque() {
		return this.estoque;
	}

	public void setEstoque(Estoque estoque) {
		this.estoque = estoque;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "m_prima_id", nullable = false, insertable = false, updatable = false)
	public MPrima getMPrima() {
		return this.MPrima;
	}

	public void setMPrima(MPrima MPrima) {
		this.MPrima = MPrima;
	}

	@Column(name = "nota_fiscal")
	public String getNotaFiscal() {
		return this.notaFiscal;
	}

	public void setNotaFiscal(String notaFiscal) {
		this.notaFiscal = notaFiscal;
	}

	@Column(name = "num_serie", nullable = false)
	public int getNumSerie() {
		return this.numSerie;
	}

	public void setNumSerie(int numSerie) {
		this.numSerie = numSerie;
	}

	@Column(name = "tipoMovimento")
	public String getTipoMovimento() {
		return this.tipoMovimento;
	}

	public void setTipoMovimento(String tipoMovimento) {
		this.tipoMovimento = tipoMovimento;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_movimento", length = 10)
	public Date getDataMovimento() {
		return this.dataMovimento;
	}

	public void setDataMovimento(Date dataMovimento) {
		this.dataMovimento = dataMovimento;
	}

}
