package com.algaworks.comercial.model;

// Generated 23/03/2016 10:12:00 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Estoque generated by hbm2java
 */
@Entity
@Table(name = "estoque", catalog = "semana")
public class Estoque implements java.io.Serializable {

	private Long id;
	private Date dataFinalizacao;
	private Date dataInicial;
	private int qtdMovimentada;
	private int qtdSaldo;
	@Enumerated(EnumType.STRING)
	private TipoMovimento tipoMovimento;
	private double valor;
	private Set<EstoqueMPrima> estoqueMPrimas = new HashSet<EstoqueMPrima>(0);
	private Set<Unidade> unidades = new HashSet<Unidade>(0);
	private Set<EstoqueProduto> estoqueProdutos = new HashSet<EstoqueProduto>(0);

	public Estoque() {
	}

	public Estoque(int qtdMovimentada, int qtdSaldo, double valor) {
		this.qtdMovimentada = qtdMovimentada;
		this.qtdSaldo = qtdSaldo;
		this.valor = valor;
	}

	public Estoque(Date dataFinalizacao, Date dataInicial, int qtdMovimentada,
			int qtdSaldo, TipoMovimento tipoMovimento, double valor,
			Set<EstoqueMPrima> estoqueMPrimas, Set<Unidade> unidades,
			Set<EstoqueProduto> estoqueProdutos) {
		this.dataFinalizacao = dataFinalizacao;
		this.dataInicial = dataInicial;
		this.qtdMovimentada = qtdMovimentada;
		this.qtdSaldo = qtdSaldo;
		this.tipoMovimento = tipoMovimento;
		this.valor = valor;
		this.estoqueMPrimas = estoqueMPrimas;
		this.unidades = unidades;
		this.estoqueProdutos = estoqueProdutos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dataFinalizacao", length = 10)
	public Date getDataFinalizacao() {
		return this.dataFinalizacao;
	}

	public void setDataFinalizacao(Date dataFinalizacao) {
		this.dataFinalizacao = dataFinalizacao;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dataInicial", length = 10)
	public Date getDataInicial() {
		return this.dataInicial;
	}

	public void setDataInicial(Date dataInicial) {
		this.dataInicial = dataInicial;
	}

	@Column(name = "qtd_Movimentada", nullable = false)
	public int getQtdMovimentada() {
		return this.qtdMovimentada;
	}

	public void setQtdMovimentada(int qtdMovimentada) {
		this.qtdMovimentada = qtdMovimentada;
	}

	@Column(name = "qtd_Saldo", nullable = false)
	public int getQtdSaldo() {
		return this.qtdSaldo;
	}

	public void setQtdSaldo(int qtdSaldo) {
		this.qtdSaldo = qtdSaldo;
	}

	@Column(name = "tipoMovimento")
	public TipoMovimento getTipoMovimento() {
		return this.tipoMovimento;
	}

	public void setTipoMovimento(TipoMovimento tipoMovimento) {
		this.tipoMovimento = tipoMovimento;
	}

	@Column(name = "valor", nullable = false, precision = 22, scale = 0)
	public double getValor() {
		return this.valor;
	}

	public void setValor(double valor) {
		this.valor = valor;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estoque")
	public Set<EstoqueMPrima> getEstoqueMPrimas() {
		return this.estoqueMPrimas;
	}

	public void setEstoqueMPrimas(Set<EstoqueMPrima> estoqueMPrimas) {
		this.estoqueMPrimas = estoqueMPrimas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estoque")
	public Set<Unidade> getUnidades() {
		return this.unidades;
	}

	public void setUnidades(Set<Unidade> unidades) {
		this.unidades = unidades;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estoque")
	public Set<EstoqueProduto> getEstoqueProdutos() {
		return this.estoqueProdutos;
	}

	public void setEstoqueProdutos(Set<EstoqueProduto> estoqueProdutos) {
		this.estoqueProdutos = estoqueProdutos;
	}

}
