package com.algaworks.comercial.model;

// Generated 23/03/2016 10:12:00 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Maquina generated by hbm2java
 */
@Entity
@Table(name = "maquina", catalog = "semana")
public class Maquina implements java.io.Serializable {

	private Long id;
	private Setor setor;
	private TipoMaquina tipoMaquina;
	private String descricao;
	private Set<Setor> setors = new HashSet<Setor>(0);
	private Set<Aquisicao> aquisicaos = new HashSet<Aquisicao>(0);

	public Maquina() {
	}

	public Maquina(Setor setor, TipoMaquina tipoMaquina, String descricao,
			Set<Setor> setors, Set<Aquisicao> aquisicaos) {
		this.setor = setor;
		this.tipoMaquina = tipoMaquina;
		this.descricao = descricao;
		this.setors = setors;
		this.aquisicaos = aquisicaos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "setor_id")
	public Setor getSetor() {
		return this.setor;
	}

	public void setSetor(Setor setor) {
		this.setor = setor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipo_Maquina_id")
	public TipoMaquina getTipoMaquina() {
		return this.tipoMaquina;
	}

	public void setTipoMaquina(TipoMaquina tipoMaquina) {
		this.tipoMaquina = tipoMaquina;
	}

	@Column(name = "descricao")
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "maquina")
	public Set<Setor> getSetors() {
		return this.setors;
	}

	public void setSetors(Set<Setor> setors) {
		this.setors = setors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "maquina")
	public Set<Aquisicao> getAquisicaos() {
		return this.aquisicaos;
	}

	public void setAquisicaos(Set<Aquisicao> aquisicaos) {
		this.aquisicaos = aquisicaos;
	}

}
