package com.algaworks.comercial.model;

// Generated 23/03/2016 10:12:00 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MPrima generated by hbm2java
 */
@Entity
@Table(name = "m_prima", catalog = "semana")
public class MPrima implements java.io.Serializable {

	private Long id;
	private String descricao;
	private double precoCompra;
	private int qtdMaxima;
	private int qtdMinima;
	private int saldoAtual;
	private String status;
	private Set<EstoqueMPrima> estoqueMPrimas = new HashSet<EstoqueMPrima>(0);
	private Set<Produto> produtos = new HashSet<Produto>(0);

	public MPrima() {
	}

	public MPrima(double precoCompra, int qtdMaxima, int qtdMinima,
			int saldoAtual) {
		this.precoCompra = precoCompra;
		this.qtdMaxima = qtdMaxima;
		this.qtdMinima = qtdMinima;
		this.saldoAtual = saldoAtual;
	}

	public MPrima(String descricao, double precoCompra, int qtdMaxima,
			int qtdMinima, int saldoAtual, String status,
			Set<EstoqueMPrima> estoqueMPrimas, Set<Produto> produtos) {
		this.descricao = descricao;
		this.precoCompra = precoCompra;
		this.qtdMaxima = qtdMaxima;
		this.qtdMinima = qtdMinima;
		this.saldoAtual = saldoAtual;
		this.status = status;
		this.estoqueMPrimas = estoqueMPrimas;
		this.produtos = produtos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "descricao")
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "preco_compra", nullable = false, precision = 22, scale = 0)
	public double getPrecoCompra() {
		return this.precoCompra;
	}

	public void setPrecoCompra(double precoCompra) {
		this.precoCompra = precoCompra;
	}

	@Column(name = "qtd_maxima", nullable = false)
	public int getQtdMaxima() {
		return this.qtdMaxima;
	}

	public void setQtdMaxima(int qtdMaxima) {
		this.qtdMaxima = qtdMaxima;
	}

	@Column(name = "qtd_minima", nullable = false)
	public int getQtdMinima() {
		return this.qtdMinima;
	}

	public void setQtdMinima(int qtdMinima) {
		this.qtdMinima = qtdMinima;
	}

	@Column(name = "saldo_atual", nullable = false)
	public int getSaldoAtual() {
		return this.saldoAtual;
	}

	public void setSaldoAtual(int saldoAtual) {
		this.saldoAtual = saldoAtual;
	}

	@Column(name = "status", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "MPrima")
	public Set<EstoqueMPrima> getEstoqueMPrimas() {
		return this.estoqueMPrimas;
	}

	public void setEstoqueMPrimas(Set<EstoqueMPrima> estoqueMPrimas) {
		this.estoqueMPrimas = estoqueMPrimas;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "m_prima_produto", catalog = "semana", joinColumns = { @JoinColumn(name = "m_prima_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "produto_id", nullable = false, updatable = false) })
	public Set<Produto> getProdutos() {
		return this.produtos;
	}

	public void setProdutos(Set<Produto> produtos) {
		this.produtos = produtos;
	}

}
