package com.algaworks.comercial.model;

// Generated 23/03/2016 10:12:00 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Setor generated by hbm2java
 */
@Entity
@Table(name = "setor", catalog = "semana")
public class Setor implements java.io.Serializable {

	private Long id;
	private Empresax empresax;
	private Maquina maquina;
	private String descricao;
	private Set<Maquina> maquinas = new HashSet<Maquina>(0);
	private Set<Funcionario> funcionarios = new HashSet<Funcionario>(0);

	public Setor() {
	}

	public Setor(Empresax empresax, Maquina maquina, String descricao,
			Set<Maquina> maquinas, Set<Funcionario> funcionarios) {
		this.empresax = empresax;
		this.maquina = maquina;
		this.descricao = descricao;
		this.maquinas = maquinas;
		this.funcionarios = funcionarios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "empresax_id")
	public Empresax getEmpresax() {
		return this.empresax;
	}

	public void setEmpresax(Empresax empresax) {
		this.empresax = empresax;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "maquina_id")
	public Maquina getMaquina() {
		return this.maquina;
	}

	public void setMaquina(Maquina maquina) {
		this.maquina = maquina;
	}

	@Column(name = "descricao")
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setor")
	public Set<Maquina> getMaquinas() {
		return this.maquinas;
	}

	public void setMaquinas(Set<Maquina> maquinas) {
		this.maquinas = maquinas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "setor")
	public Set<Funcionario> getFuncionarios() {
		return this.funcionarios;
	}

	public void setFuncionarios(Set<Funcionario> funcionarios) {
		this.funcionarios = funcionarios;
	}

}
