package com.algaworks.comercial.model;

// Generated 23/03/2016 10:12:00 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StockCategoryId generated by hbm2java
 */
@Embeddable
public class StockCategoryId implements java.io.Serializable {

	private int stockId;
	private int categoryId;

	public StockCategoryId() {
	}

	public StockCategoryId(int stockId, int categoryId) {
		this.stockId = stockId;
		this.categoryId = categoryId;
	}

	@Column(name = "STOCK_ID", nullable = false)
	public int getStockId() {
		return this.stockId;
	}

	public void setStockId(int stockId) {
		this.stockId = stockId;
	}

	@Column(name = "CATEGORY_ID", nullable = false)
	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StockCategoryId))
			return false;
		StockCategoryId castOther = (StockCategoryId) other;

		return (this.getStockId() == castOther.getStockId())
				&& (this.getCategoryId() == castOther.getCategoryId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getStockId();
		result = 37 * result + this.getCategoryId();
		return result;
	}

}
