package com.algaworks.comercial.model;

// Generated 23/03/2016 10:12:00 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StockCategory generated by hbm2java
 */
@Entity
@Table(name = "stock_category", catalog = "semana")
public class StockCategory implements java.io.Serializable {

	private StockCategoryId id;
	private Category category;
	private Stock stock;
	private Date createdDate;
	private String createdBy;

	public StockCategory() {
	}

	public StockCategory(StockCategoryId id, Category category, Stock stock,
			Date createdDate, String createdBy) {
		this.id = id;
		this.category = category;
		this.stock = stock;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "stockId", column = @Column(name = "STOCK_ID", nullable = false)),
			@AttributeOverride(name = "categoryId", column = @Column(name = "CATEGORY_ID", nullable = false)) })
	public StockCategoryId getId() {
		return this.id;
	}

	public void setId(StockCategoryId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CATEGORY_ID", nullable = false, insertable = false, updatable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STOCK_ID", nullable = false, insertable = false, updatable = false)
	public Stock getStock() {
		return this.stock;
	}

	public void setStock(Stock stock) {
		this.stock = stock;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", nullable = false, length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 10)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

}
