package com.algaworks.comercial.model;

// Generated 23/03/2016 10:12:00 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoMaquina generated by hbm2java
 */
@Entity
@Table(name = "tipo_maquina", catalog = "semana")
public class TipoMaquina implements java.io.Serializable {

	private Long id;
	private String descricao;
	private Set<Maquina> maquinas = new HashSet<Maquina>(0);

	public TipoMaquina() {
	}

	public TipoMaquina(String descricao, Set<Maquina> maquinas) {
		this.descricao = descricao;
		this.maquinas = maquinas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "descricao")
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoMaquina")
	public Set<Maquina> getMaquinas() {
		return this.maquinas;
	}

	public void setMaquinas(Set<Maquina> maquinas) {
		this.maquinas = maquinas;
	}

}
